-- Daleth Sales Hub - Supabase schema inicial
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role text default 'commercial',
  created_at timestamptz default now()
);

create table if not exists companies (
  id bigint generated by default as identity primary key,
  name text not null,
  segment text,
  cnpj text,
  site text,
  status text default 'Prospect',
  phone text,
  email text,
  notes text,
  created_at timestamptz default now()
);

create table if not exists contacts (
  id bigint generated by default as identity primary key,
  company_id bigint references companies(id) on delete set null,
  name text not null,
  role text,
  email text,
  phone text,
  whatsapp text,
  linkedin text,
  type text default 'Decisor',
  notes text,
  created_at timestamptz default now()
);

create table if not exists deals (
  id bigint generated by default as identity primary key,
  title text not null,
  company_id bigint references companies(id) on delete set null,
  contact_id bigint references contacts(id) on delete set null,
  product text,
  value numeric default 0,
  setup numeric default 0,
  stage text default 'Lead Captado',
  owner text,
  probability int default 30,
  close_date date,
  description text,
  next_step text,
  priority text default 'Média',
  created_at timestamptz default now()
);

create table if not exists deal_notes (
  id bigint generated by default as identity primary key,
  deal_id bigint references deals(id) on delete cascade,
  user_name text not null,
  note_date date default current_date,
  text text not null,
  created_at timestamptz default now()
);

create table if not exists activities (
  id bigint generated by default as identity primary key,
  deal_id bigint references deals(id) on delete cascade,
  type text default 'Follow-up',
  title text not null,
  due_date date,
  owner text,
  status text default 'Pendente',
  notes text,
  created_at timestamptz default now()
);

-- RLS deverá ser ativado na etapa de autenticação real.
