-- Daleth Sales Hub - Supabase Fase 2
-- Schema alinhado com o frontend atual.
-- Seguro para rodar mais de uma vez: usa create table if not exists e add column if not exists.

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text,
  email text,
  full_name text not null,
  role text not null default 'Comercial',
  can_view_dashboard boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table profiles add column if not exists name text;
alter table profiles add column if not exists email text;
alter table profiles add column if not exists full_name text;
alter table profiles add column if not exists role text not null default 'Comercial';
alter table profiles add column if not exists can_view_dashboard boolean not null default false;
alter table profiles add column if not exists created_at timestamptz not null default now();
alter table profiles add column if not exists updated_at timestamptz not null default now();

update profiles
set full_name = coalesce(full_name, name, auth_users.email, 'Usuario'),
    name = coalesce(name, full_name, auth_users.email, 'Usuario')
from auth.users auth_users
where profiles.id = auth_users.id
  and (profiles.full_name is null or profiles.name is null);

update profiles
set full_name = coalesce(full_name, name, 'Usuario'),
    name = coalesce(name, full_name, 'Usuario')
where full_name is null
   or name is null;

alter table profiles alter column name set not null;
alter table profiles alter column full_name set not null;

create or replace function create_profile_for_auth_user()
returns trigger as $$
begin
  insert into public.profiles (id, name, email, full_name, role, can_view_dashboard)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', new.email, 'Usuario'),
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', new.email, 'Usuario'),
    coalesce(new.raw_user_meta_data->>'role', 'Comercial'),
    coalesce((new.raw_user_meta_data->>'can_view_dashboard')::boolean, false)
  )
  on conflict (id) do update
  set name = coalesce(public.profiles.name, excluded.name),
      email = excluded.email,
      full_name = coalesce(public.profiles.full_name, excluded.full_name),
      role = coalesce(public.profiles.role, excluded.role),
      can_view_dashboard = public.profiles.can_view_dashboard or excluded.can_view_dashboard;

  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists auth_users_create_profile on auth.users;
create trigger auth_users_create_profile
after insert on auth.users
for each row execute function create_profile_for_auth_user();

insert into public.profiles (id, name, email, full_name, role, can_view_dashboard)
select
  users.id,
  coalesce(users.raw_user_meta_data->>'full_name', users.email, 'Usuario'),
  users.email,
  coalesce(users.raw_user_meta_data->>'full_name', users.email, 'Usuario'),
  coalesce(users.raw_user_meta_data->>'role', 'Comercial'),
  coalesce((users.raw_user_meta_data->>'can_view_dashboard')::boolean, false)
from auth.users users
on conflict (id) do update
set name = coalesce(public.profiles.name, excluded.name),
    email = excluded.email,
    full_name = coalesce(public.profiles.full_name, excluded.full_name),
    role = coalesce(public.profiles.role, excluded.role),
    can_view_dashboard = public.profiles.can_view_dashboard or excluded.can_view_dashboard;

create table if not exists crm_state (
  key text primary key,
  data jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists products_name_lower_idx on products (lower(name));

create table if not exists companies (
  id bigint generated by default as identity primary key,
  legacy_id text,
  name text not null,
  segment text,
  cnpj text,
  site text,
  website text,
  status text not null default 'Prospect',
  phone text,
  email text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table companies add column if not exists legacy_id text;
alter table companies add column if not exists website text;
alter table companies add column if not exists updated_at timestamptz not null default now();

create index if not exists companies_legacy_id_idx on companies (legacy_id);
create index if not exists companies_name_idx on companies (name);

create table if not exists contacts (
  id bigint generated by default as identity primary key,
  legacy_id text,
  company_id bigint references companies(id) on delete set null,
  name text not null,
  role text,
  email text,
  phone text,
  whatsapp text,
  linkedin text,
  type text,
  contact_type text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table contacts add column if not exists legacy_id text;
alter table contacts add column if not exists contact_type text;
alter table contacts add column if not exists updated_at timestamptz not null default now();

create index if not exists contacts_legacy_id_idx on contacts (legacy_id);
create index if not exists contacts_company_id_idx on contacts (company_id);
create index if not exists contacts_name_idx on contacts (name);

create table if not exists opportunities (
  id bigint generated by default as identity primary key,
  legacy_id text,
  company_id bigint references companies(id) on delete set null,
  contact_id bigint references contacts(id) on delete set null,
  title text not null,
  product text,
  value numeric not null default 0,
  setup_value numeric not null default 0,
  contract_months integer not null default 12,
  probability integer not null default 30,
  expected_close_date date,
  status text,
  stage text not null default 'Lead Captado',
  description text,
  next_step text,
  priority text not null default 'Média',
  owner text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table opportunities add column if not exists legacy_id text;
alter table opportunities add column if not exists setup_value numeric not null default 0;
alter table opportunities add column if not exists contract_months integer not null default 12;
alter table opportunities add column if not exists expected_close_date date;
alter table opportunities add column if not exists status text;
alter table opportunities add column if not exists next_step text;
alter table opportunities add column if not exists priority text not null default 'Média';
alter table opportunities add column if not exists owner text;
alter table opportunities add column if not exists updated_at timestamptz not null default now();

create index if not exists opportunities_legacy_id_idx on opportunities (legacy_id);
create index if not exists opportunities_company_id_idx on opportunities (company_id);
create index if not exists opportunities_contact_id_idx on opportunities (contact_id);
create index if not exists opportunities_stage_idx on opportunities (stage);

create table if not exists activities (
  id bigint generated by default as identity primary key,
  legacy_id text,
  opportunity_id bigint references opportunities(id) on delete cascade,
  title text not null,
  type text not null default 'Follow-up',
  due_date date,
  due_time time,
  meeting_link text,
  status text not null default 'Pendente',
  notes text,
  owner text,
  activity_type text not null default 'Follow-up',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table activities add column if not exists legacy_id text;
alter table activities add column if not exists opportunity_id bigint references opportunities(id) on delete cascade;
alter table activities add column if not exists type text not null default 'Follow-up';
alter table activities add column if not exists activity_type text not null default 'Follow-up';
alter table activities add column if not exists due_time time;
alter table activities add column if not exists meeting_link text;
alter table activities add column if not exists updated_at timestamptz not null default now();

create index if not exists activities_legacy_id_idx on activities (legacy_id);
create index if not exists activities_opportunity_id_idx on activities (opportunity_id);
create index if not exists activities_due_date_idx on activities (due_date);

create table if not exists notes (
  id bigint generated by default as identity primary key,
  legacy_id text,
  opportunity_id bigint references opportunities(id) on delete cascade,
  user_name text not null,
  note_date date not null default current_date,
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table notes add column if not exists legacy_id text;
alter table notes add column if not exists opportunity_id bigint references opportunities(id) on delete cascade;
alter table notes add column if not exists updated_at timestamptz not null default now();

create index if not exists notes_legacy_id_idx on notes (legacy_id);
create index if not exists notes_opportunity_id_idx on notes (opportunity_id);
create index if not exists notes_note_date_idx on notes (note_date);

create table if not exists contracts (
  id bigint generated by default as identity primary key,
  legacy_id text,
  company_id bigint references companies(id) on delete set null,
  opportunity_id bigint references opportunities(id) on delete set null,
  product text,
  owner text,
  mrr numeric not null default 0,
  setup numeric not null default 0,
  contract_months integer not null default 12,
  start_date date,
  end_date date,
  status text not null default 'Ativo',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table contracts add column if not exists legacy_id text;
alter table contracts add column if not exists opportunity_id bigint references opportunities(id) on delete set null;
alter table contracts add column if not exists updated_at timestamptz not null default now();

create index if not exists contracts_legacy_id_idx on contracts (legacy_id);
create index if not exists contracts_company_id_idx on contracts (company_id);
create index if not exists contracts_opportunity_id_idx on contracts (opportunity_id);
create index if not exists contracts_end_date_idx on contracts (end_date);

drop index if exists companies_legacy_id_unique_idx;
drop index if exists contacts_legacy_id_unique_idx;
drop index if exists opportunities_legacy_id_unique_idx;
drop index if exists activities_legacy_id_unique_idx;
drop index if exists notes_legacy_id_unique_idx;
drop index if exists contracts_legacy_id_unique_idx;

with duplicated_companies as (
  select id, first_value(id) over (partition by legacy_id order by created_at nulls last, id::text) as keep_id
  from companies
  where legacy_id is not null
)
update contacts
set company_id = duplicated_companies.keep_id
from duplicated_companies
where contacts.company_id = duplicated_companies.id
  and duplicated_companies.id <> duplicated_companies.keep_id;

with duplicated_companies as (
  select id, first_value(id) over (partition by legacy_id order by created_at nulls last, id::text) as keep_id
  from companies
  where legacy_id is not null
)
update opportunities
set company_id = duplicated_companies.keep_id
from duplicated_companies
where opportunities.company_id = duplicated_companies.id
  and duplicated_companies.id <> duplicated_companies.keep_id;

with duplicated_companies as (
  select id, first_value(id) over (partition by legacy_id order by created_at nulls last, id::text) as keep_id
  from companies
  where legacy_id is not null
)
update contracts
set company_id = duplicated_companies.keep_id
from duplicated_companies
where contracts.company_id = duplicated_companies.id
  and duplicated_companies.id <> duplicated_companies.keep_id;

with duplicated_companies as (
  select id, first_value(id) over (partition by legacy_id order by created_at nulls last, id::text) as keep_id
  from companies
  where legacy_id is not null
)
delete from companies
using duplicated_companies
where companies.id = duplicated_companies.id
  and duplicated_companies.id <> duplicated_companies.keep_id;

with duplicated_contacts as (
  select id, first_value(id) over (partition by legacy_id order by created_at nulls last, id::text) as keep_id
  from contacts
  where legacy_id is not null
)
update opportunities
set contact_id = duplicated_contacts.keep_id
from duplicated_contacts
where opportunities.contact_id = duplicated_contacts.id
  and duplicated_contacts.id <> duplicated_contacts.keep_id;

with duplicated_contacts as (
  select id, first_value(id) over (partition by legacy_id order by created_at nulls last, id::text) as keep_id
  from contacts
  where legacy_id is not null
)
delete from contacts
using duplicated_contacts
where contacts.id = duplicated_contacts.id
  and duplicated_contacts.id <> duplicated_contacts.keep_id;

with duplicated_opportunities as (
  select id, first_value(id) over (partition by legacy_id order by created_at nulls last, id::text) as keep_id
  from opportunities
  where legacy_id is not null
)
update activities
set opportunity_id = duplicated_opportunities.keep_id
from duplicated_opportunities
where activities.opportunity_id = duplicated_opportunities.id
  and duplicated_opportunities.id <> duplicated_opportunities.keep_id;

with duplicated_opportunities as (
  select id, first_value(id) over (partition by legacy_id order by created_at nulls last, id::text) as keep_id
  from opportunities
  where legacy_id is not null
)
update notes
set opportunity_id = duplicated_opportunities.keep_id
from duplicated_opportunities
where notes.opportunity_id = duplicated_opportunities.id
  and duplicated_opportunities.id <> duplicated_opportunities.keep_id;

with duplicated_opportunities as (
  select id, first_value(id) over (partition by legacy_id order by created_at nulls last, id::text) as keep_id
  from opportunities
  where legacy_id is not null
)
update contracts
set opportunity_id = duplicated_opportunities.keep_id
from duplicated_opportunities
where contracts.opportunity_id = duplicated_opportunities.id
  and duplicated_opportunities.id <> duplicated_opportunities.keep_id;

with duplicated_opportunities as (
  select id, first_value(id) over (partition by legacy_id order by created_at nulls last, id::text) as keep_id
  from opportunities
  where legacy_id is not null
)
delete from opportunities
using duplicated_opportunities
where opportunities.id = duplicated_opportunities.id
  and duplicated_opportunities.id <> duplicated_opportunities.keep_id;

with duplicated_activities as (
  select id, first_value(id) over (partition by legacy_id order by created_at nulls last, id::text) as keep_id
  from activities
  where legacy_id is not null
)
delete from activities
using duplicated_activities
where activities.id = duplicated_activities.id
  and duplicated_activities.id <> duplicated_activities.keep_id;

with duplicated_notes as (
  select id, first_value(id) over (partition by legacy_id order by created_at nulls last, id::text) as keep_id
  from notes
  where legacy_id is not null
)
delete from notes
using duplicated_notes
where notes.id = duplicated_notes.id
  and duplicated_notes.id <> duplicated_notes.keep_id;

with duplicated_contracts as (
  select id, first_value(id) over (partition by legacy_id order by created_at nulls last, id::text) as keep_id
  from contracts
  where legacy_id is not null
)
delete from contracts
using duplicated_contracts
where contracts.id = duplicated_contracts.id
  and duplicated_contracts.id <> duplicated_contracts.keep_id;

create unique index if not exists companies_legacy_id_unique_idx on companies (legacy_id);
create unique index if not exists contacts_legacy_id_unique_idx on contacts (legacy_id);
create unique index if not exists opportunities_legacy_id_unique_idx on opportunities (legacy_id);
create unique index if not exists activities_legacy_id_unique_idx on activities (legacy_id);
create unique index if not exists notes_legacy_id_unique_idx on notes (legacy_id);
create unique index if not exists contracts_legacy_id_unique_idx on contracts (legacy_id);

-- Compatibilidade para bases antigas que ainda tenham deals/deal_notes.
-- A migracao de dados deve copiar deals -> opportunities e deal_notes -> notes antes de remover tabelas antigas.

create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists profiles_set_updated_at on profiles;
create trigger profiles_set_updated_at
before update on profiles
for each row execute function set_updated_at();

drop trigger if exists products_set_updated_at on products;
create trigger products_set_updated_at
before update on products
for each row execute function set_updated_at();

drop trigger if exists companies_set_updated_at on companies;
create trigger companies_set_updated_at
before update on companies
for each row execute function set_updated_at();

drop trigger if exists contacts_set_updated_at on contacts;
create trigger contacts_set_updated_at
before update on contacts
for each row execute function set_updated_at();

drop trigger if exists opportunities_set_updated_at on opportunities;
create trigger opportunities_set_updated_at
before update on opportunities
for each row execute function set_updated_at();

drop trigger if exists activities_set_updated_at on activities;
create trigger activities_set_updated_at
before update on activities
for each row execute function set_updated_at();

drop trigger if exists notes_set_updated_at on notes;
create trigger notes_set_updated_at
before update on notes
for each row execute function set_updated_at();

drop trigger if exists contracts_set_updated_at on contracts;
create trigger contracts_set_updated_at
before update on contracts
for each row execute function set_updated_at();

insert into products (name)
values
  ('SAC+'),
  ('SAC 24h'),
  ('Inside Sales'),
  ('Help Desk'),
  ('Back Office'),
  ('Ouvidorias'),
  ('Custom')
on conflict do nothing;

-- RLS - Fase 2
-- Regras:
-- - Usuario autenticado le dados do CRM.
-- - CEO e Comercial criam/editam/excluem dados comerciais.
-- - Reserva apenas leitura.
-- - Profiles: cada usuario le o proprio perfil; CEO gerencia perfis.

create or replace function current_profile_role()
returns text as $$
  select coalesce(
    (
      select p.role
      from public.profiles p
      where p.id = auth.uid()
      limit 1
    ),
    ''
  );
$$ language sql stable security definer set search_path = public;

create or replace function can_write_crm()
returns boolean as $$
  select current_profile_role() in ('CEO', 'Comercial');
$$ language sql stable security definer set search_path = public;

create or replace function is_ceo()
returns boolean as $$
  select current_profile_role() = 'CEO';
$$ language sql stable security definer set search_path = public;

alter table profiles enable row level security;
alter table crm_state enable row level security;
alter table products enable row level security;
alter table companies enable row level security;
alter table contacts enable row level security;
alter table opportunities enable row level security;
alter table activities enable row level security;
alter table notes enable row level security;
alter table contracts enable row level security;

drop policy if exists profiles_select_own_or_ceo on profiles;
create policy profiles_select_own_or_ceo
on profiles
for select
to authenticated
using (id = auth.uid() or is_ceo());

drop policy if exists profiles_update_own_or_ceo on profiles;
drop policy if exists profiles_update_ceo on profiles;
create policy profiles_update_ceo
on profiles
for update
to authenticated
using (is_ceo())
with check (is_ceo());

drop policy if exists profiles_insert_ceo on profiles;
create policy profiles_insert_ceo
on profiles
for insert
to authenticated
with check (is_ceo());

drop policy if exists profiles_delete_ceo on profiles;
create policy profiles_delete_ceo
on profiles
for delete
to authenticated
using (is_ceo());

drop policy if exists crm_state_select_authenticated on crm_state;
create policy crm_state_select_authenticated
on crm_state
for select
to authenticated
using (true);

drop policy if exists crm_state_write_ceo_comercial on crm_state;
create policy crm_state_write_ceo_comercial
on crm_state
for all
to authenticated
using (can_write_crm())
with check (can_write_crm());

drop policy if exists products_select_authenticated on products;
create policy products_select_authenticated
on products
for select
to authenticated
using (true);

drop policy if exists products_write_ceo_comercial on products;
create policy products_write_ceo_comercial
on products
for all
to authenticated
using (can_write_crm())
with check (can_write_crm());

drop policy if exists companies_select_authenticated on companies;
create policy companies_select_authenticated
on companies
for select
to authenticated
using (true);

drop policy if exists companies_write_ceo_comercial on companies;
create policy companies_write_ceo_comercial
on companies
for all
to authenticated
using (can_write_crm())
with check (can_write_crm());

drop policy if exists contacts_select_authenticated on contacts;
create policy contacts_select_authenticated
on contacts
for select
to authenticated
using (true);

drop policy if exists contacts_write_ceo_comercial on contacts;
create policy contacts_write_ceo_comercial
on contacts
for all
to authenticated
using (can_write_crm())
with check (can_write_crm());

drop policy if exists opportunities_select_authenticated on opportunities;
create policy opportunities_select_authenticated
on opportunities
for select
to authenticated
using (true);

drop policy if exists opportunities_write_ceo_comercial on opportunities;
create policy opportunities_write_ceo_comercial
on opportunities
for all
to authenticated
using (can_write_crm())
with check (can_write_crm());

drop policy if exists activities_select_authenticated on activities;
create policy activities_select_authenticated
on activities
for select
to authenticated
using (true);

drop policy if exists activities_write_ceo_comercial on activities;
create policy activities_write_ceo_comercial
on activities
for all
to authenticated
using (can_write_crm())
with check (can_write_crm());

drop policy if exists notes_select_authenticated on notes;
create policy notes_select_authenticated
on notes
for select
to authenticated
using (true);

drop policy if exists notes_write_ceo_comercial on notes;
create policy notes_write_ceo_comercial
on notes
for all
to authenticated
using (can_write_crm())
with check (can_write_crm());

drop policy if exists contracts_select_authenticated on contracts;
create policy contracts_select_authenticated
on contracts
for select
to authenticated
using (true);

drop policy if exists contracts_write_ceo_comercial on contracts;
create policy contracts_write_ceo_comercial
on contracts
for all
to authenticated
using (can_write_crm())
with check (can_write_crm());
